名字: 刷课
 
在: 
推:
分支: [主要的]
  #是否开始每天8点定时刷课，若要开启请把下面两行注释去掉
  #计划:
  # - cron: "0 8 * * * "
    
工作: 
开始:
连续运行: Ubuntu-最新版# 在最新版本的人的本质操作系统环境下运行
步伐: # 要执行的步骤
      - 名字: 拷贝代码
使用: 动作/签出@v3# 用于将开源代码库代码仓库的代码拷贝到工作目录中
 
      - 名字: 设置大蟒环境
使用: 操作/设置-python@v2# 用于设置计算机编程语言环境,它允许你指定要在工作环境中使用的计算机编程语言版本
随着:
python版本: '3.9'  # 选择要用的计算机编程语言版本
 
      - 名字: 安装依赖包
奔跑: | # 安装依赖包
pip安装-r ./requirements.txt
          
      
      - 名字: 运行main.py
        run: python main.py -u 学习通账号17620068262 -p 学习通密码Aa1378868666. -l 244403509 #课程id，默认为心理课的
